openapi: 3.0.2
info:
  title: SwipeRestApi
  version: "1.0.0"
paths:
  /auth/login:
    get:
      parameters: 
      - in: header
        name: HTTP_AUTHORIZATION
        schema:
          type: string
          format: token
        required: true
      description: User login
      responses:
        '200':
          description: User verified. Get uid and email/phone
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '403':
          description: Either no auth token provided or token is invalid
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    no_auth:
                      description: No authentication token provided
                      type: string
                    invalid:
                      description: valid authentication token provided
                      type: string
        '500':
          description: The user provided with the auth token is not a valid Firebase user, it has no Firebase UID
                  
components:
  schemas:
    User:
      properties:
        user:
          description: Email or Phone number
          type: string
        auth:
          description: UID 
          type: string