version: "3.8"

services:
  api:
    build:
      context: .
    command: gunicorn swipe.wsgi.application --bind 0.0.0.0:8000
    volumes:
      - ./:/urs/src/project
      - static_volume:/home/api/static
      - media_volume:/home/api/media
      expose:
        - 8000
      env_file:
        - env
      depends_on:
        - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/api/static
      - media_volume:/home/api/media
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
