# Generated by Django 3.2.5 on 2021-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0002_alter_user_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractuser',
            name='uid',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
