# Generated by Django 3.2.5 on 2021-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0003_customabstractuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customabstractuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
