# Generated by Django 3.2.5 on 2021-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0004_alter_customabstractuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Клиент'), ('AGENT', 'Агент'), ('NOTARY', 'Нотариус'), ('DEPART', 'Отдел продаж')], default='USER', max_length=8),
        ),
    ]
