# Generated by Django 3.2.5 on 2021-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0006_auto_20210708_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customabstractuser',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
