# Generated by Django 3.2.5 on 2021-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0007_alter_customabstractuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
