# Generated by Django 3.2.5 on 2021-07-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0008_alter_user_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
    ]
