# Generated by Django 3.2.5 on 2021-07-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0009_remove_attachment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='created',
        ),
    ]
