# Generated by Django 3.2.5 on 2021-07-11 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0010_remove_attachment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
