# Generated by Django 3.2.5 on 2021-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0017_alter_standpipe_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='schema_in_house',
            field=models.ImageField(blank=True, null=True, upload_to='media/flats/schema_in_house'),
        ),
    ]
