# Generated by Django 3.2.5 on 2021-07-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0018_alter_flat_schema_in_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
