# Generated by Django 3.2.5 on 2021-07-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0019_flat_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='Odessa', max_length=150),
            preserve_default=False,
        ),
    ]
