# Generated by Django 3.2.5 on 2021-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0020_house_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='requesttochest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('MANY', 'Многоквартирный'), ('ONE', 'Частный')], default='MANE', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('MANY', 'Многоквартирный'), ('ONE', 'Частный')], default='FLAT', max_length=6, null=True),
        ),
    ]
