# Generated by Django 3.2.5 on 2021-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0021_auto_20210715_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
