# Generated by Django 3.2.5 on 2021-07-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0026_auto_20210716_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default=1, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
