# Generated by Django 3.2.5 on 2021-07-16 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0028_rename_type_post_living_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='_db.house'),
            preserve_default=False,
        ),
    ]
