# Generated by Django 3.2.5 on 2021-07-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0030_userfavorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorites',
            old_name='posts',
            new_name='post',
        ),
    ]
