# Generated by Django 3.2.5 on 2021-07-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0032_auto_20210717_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilter',
            old_name='district',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userfilter',
            old_name='microdistrict',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='role',
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('MANY', 'Многоквартирный'), ('ONE', 'Частный'), ('NOVOSTROY', 'Новострой'), ('SECONDARY', 'Вторичный рынок'), ('COTTAGES', 'Коттеджи')], default='MANE', max_length=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='living_type',
            field=models.CharField(blank=True, choices=[('MANY', 'Многоквартирный'), ('ONE', 'Частный'), ('NOVOSTROY', 'Новострой'), ('SECONDARY', 'Вторичный рынок'), ('COTTAGES', 'Коттеджи')], default='MANY', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='status',
            field=models.CharField(blank=True, choices=[('FLATS', 'Квартиры'), ('OFFICES', 'Офисы')], default='FLATS', max_length=7, null=True),
        ),
    ]
