# Generated by Django 3.2.5 on 2021-07-18 11:02

import _db.models.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0033_auto_20210717_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikers',
            field=models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='media/', validators=[_db.models.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/documents', validators=[_db.models.validators.validate_file_extension]),
        ),
    ]
