# Generated by Django 3.2.5 on 2021-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0034_auto_20210718_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
