# Generated by Django 3.2.5 on 2021-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0035_post_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='color',
            field=models.CharField(blank=True, choices=[('PINK', 'Розовый'), ('GREEN', 'Зеленый')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='phrase',
            field=models.CharField(blank=True, choices=[('GIFT', 'Подарок при покупке'), ('TRADE', 'Возможен торг'), ('SEA', 'Квартира у моря'), ('SLEEP', 'В спальном районе'), ('PRICE', 'Вам повезло с ценой'), ('BIG_FAMILY', 'Для большой семьи'), ('FAMILY', 'Семейное гнездышко'), ('CAR_PARK', 'Отдельная парковка')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
