# Generated by Django 3.2.5 on 2021-07-19 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0036_auto_20210719_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='_db.post'),
        ),
    ]
