# Generated by Django 3.2.5 on 2021-07-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0037_auto_20210719_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
