# Generated by Django 3.2.5 on 2021-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0041_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customabstractuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customabstractuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last_name'),
        ),
    ]
