# Generated by Django 3.2.5 on 2021-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0042_auto_20210722_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
