# Generated by Django 3.2.5 on 2021-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0043_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
