# Generated by Django 3.2.5 on 2021-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0045_alter_post_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customabstractuser',
            name='uid',
        ),
        migrations.AlterField(
            model_name='customabstractuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
