# Generated by Django 3.2.5 on 2021-07-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0047_alter_customabstractuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('PRICE', 'Некорректная цена'), ('PHOTO', 'Некорректное фото'), ('DESC', 'Некорректное описание'), ('ANY', 'Другое...')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='reject_message',
            field=models.CharField(blank=True, choices=[('PRICE', 'Некорректная цена'), ('PHOTO', 'Некорректное фото'), ('DESC', 'Некорректное описание'), ('ANY', 'Другое...')], max_length=5, null=True),
        ),
    ]
