# Generated by Django 3.2.5 on 2021-08-01 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0049_complaint_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFavorites',
        ),
    ]
