# Generated by Django 3.2.5 on 2021-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0050_auto_20210801_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
