# Generated by Django 3.2.5 on 2021-08-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0052_auto_20210809_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
