# Generated by Django 3.2.5 on 2021-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0053_auto_20210811_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintoken',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
